SELECT a.CUSTOMERID,b.CUANTIDAD_DE_VENTA,b.DATA_VENTA
FROM CUSTOMER a
JOIN ORDER b ON a.CUSTOMERID=b.CUSTOMERID
WHERE a.FECHA_DE_NASCIMENTO = GETDATE ('YYYY-MM-DD')
AND b.CUANTIDAD_DE_VENTA >1500 
AND MONTH(b.DATA_VENTA)=01 
AND YEAR(b.DATA_VENTA)=2020 
