SELECT TOP 5 b.NOMBRE_VENDEDOR, b.APELLIDO_VENDEDOR, 
COUNT(a.CUANTIDAD_DE_VENTA) AS 'TOTALE_VENTAS',
SUM(a.CUANTIDAD_DE_PRODUCTOS) AS 'CUANTIDAD_VENTA',
SUM (a.PRECO_DE_VENTA) AS 'MONTO_TOTAL_TRANSACCIONADO',
MONTH(a.DATA_VENTA) AS 'DATA_VENTA'
FROM ORDER a 
JOIN CUSTOMER b ON a.CUSTOMERID=b.CUSTOMERID
JOIN CATEGORY c ON b.ITEMID = c.ITEMID
WHERE .CATEGORIA = 'CELULARES Y TELEFONOS' 
AND YEAR(a.DATA_VENTA)=2020
GROUP by b.NOMBRE_VENDEDOR,b.APELLIDO_VENDEDOR, MONTH(a.DATA_VENTA)
